name: Colin Stringer
favicon: null
layout_spectrum: 0.35907314880751073
typography_spectrum: 0.04626732715405524
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25039853528141975
  lightness: 0.6657490828074515
  saturation: 0.3785177662502974
  rhythmicContrast: 0.7098346264101565
purpose: []
