name: Colin Stringer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.096
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#464854'
    - '#f9f9f9'
    - '#0f0e00'
    - '#878a9f'
    - '#c6c3cc'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.7098346264101565
purpose: []
